// Bridging header exposing the `vpn21-core` C ABI to Swift.
// This file is committed only as a reference; the real one is generated by
// cbindgen during the Rust build step (see `tools/gen-c-headers.sh`).
#ifndef VPN21_H
#define VPN21_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int  vpn21_init(const char* app_dir, int verbose);
char* vpn21_profile_parse(const char* id, const char* label, const char* json);
char* vpn21_start(const char* profile_json, int tun_fd, int mtu,
                  const char* ipv4, int mask, int dns_port);
char* vpn21_stop(void);
char* vpn21_status(void);
char* vpn21_logs(int limit);
void  vpn21_logs_clear(void);
void  vpn21_string_free(char* s);

#ifdef __cplusplus
}
#endif

#endif // VPN21_H
